# Generated by Django 5.2.3 on 2025-06-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('idD', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=25)),
                ('motive', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('idA', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('int_area', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='CoreContent',
            fields=[
                ('idC', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('core_cont', models.CharField(max_length=30)),
                ('int_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.interestarea')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idP', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('statement', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField()),
                ('difficult_level', models.PositiveSmallIntegerField(default=0)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('pk', models.CompositePrimaryKey('question', 'option', blank=True, editable=False, primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='quiz2.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_to_question', to='quiz2.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(through='quiz2.Options', to='quiz2.question'),
        ),
        migrations.AddField(
            model_name='option',
            name='question_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='quiz2.question'),
        ),
        migrations.AddIndex(
            model_name='interestarea',
            index=models.Index(fields=['int_area'], name='quiz2_inter_int_are_232545_idx'),
        ),
        migrations.AddIndex(
            model_name='corecontent',
            index=models.Index(fields=['core_cont'], name='quiz2_corec_core_co_9cce84_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['option'], name='quiz2_optio_option_b86258_idx'),
        ),
    ]
