# Generated by Django 5.2.3 on 2025-06-23 17:16

import apps.quiz2.utils
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('idD', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('dimension', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('enviroment', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=25)),
                ('motive', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('profesion', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['profesion'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('interviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respondant',
            fields=[
                ('respondant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('Femenino', 'Female'), ('Masculino', 'Male')])),
                ('nationality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('level_PBE', models.PositiveSmallIntegerField()),
                ('title', models.CharField(choices=[('Estudiante', 'Student'), ('Grado/Licenciatura-Diplomatura', 'Grade'), ('Master/Postgrado', 'Master'), ('Doctorado', 'Doctorate')])),
                ('year_title', models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.quiz2.utils.year])),
                ('PBE_knownledge', models.BooleanField(default=False)),
                ('PBE_training', models.CharField(max_length=30)),
                ('speciality', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('idA', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('int_area', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='CoreContent',
            fields=[
                ('idC', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('core_cont', models.CharField(max_length=30)),
                ('int_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.interestarea')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idP', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField()),
                ('difficult_level', models.PositiveSmallIntegerField(default=0)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz2.dimension')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='quiz2.option')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('pk', models.CompositePrimaryKey('question', 'option', blank=True, editable=False, primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='quiz2.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_to_question', to='quiz2.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(related_name='option_values', through='quiz2.Options', to='quiz2.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.CharField(editable=False, max_length=25)),
                ('time', models.TimeField(editable=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('respondant', 'question', blank=True, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz2.question')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('profesional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz2.respondant')),
                ('supervisor', models.BooleanField(default=False)),
                ('dedicationW', models.PositiveSmallIntegerField(default=0)),
                ('years', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Doctorado',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz2.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Grade',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz2.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
                ('course', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Master',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz2.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
                ('master', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Resprofs',
            fields=[
                ('pk', models.CompositePrimaryKey('profesion', 'respondant', blank=True, editable=False, primary_key=True, serialize=False)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz2.profesion')),
                ('respondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz2.respondant')),
            ],
        ),
        migrations.AddField(
            model_name='respondant',
            name='profesions',
            field=models.ManyToManyField(related_name='profesional_area_user', through='quiz2.Resprofs', to='quiz2.profesion'),
        ),
        migrations.AddField(
            model_name='respondant',
            name='questions',
            field=models.ManyToManyField(related_name='respondant_answer_to_question', through='quiz2.Answer', to='quiz2.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='respondant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz2.respondant'),
        ),
        migrations.AddIndex(
            model_name='interestarea',
            index=models.Index(fields=['int_area'], name='quiz2_inter_int_are_232545_idx'),
        ),
        migrations.AddIndex(
            model_name='corecontent',
            index=models.Index(fields=['core_cont'], name='quiz2_corec_core_co_9cce84_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['statement'], name='quiz2_quest_stateme_b60e55_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['option'], name='quiz2_optio_option_b86258_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_doctorado',
            index=models.Index(fields=['academic_lvl'], name='quiz2_stu_d_academi_818aac_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_grade',
            index=models.Index(fields=['academic_lvl'], name='quiz2_stu_g_academi_749745_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_master',
            index=models.Index(fields=['academic_lvl'], name='quiz2_stu_m_academi_f82155_idx'),
        ),
    ]
