# Generated by Django 5.2.3 on 2025-06-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz2', '0002_dedication_profesional_activities_envprof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimension',
            name='orden',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interestarea',
            name='orden',
            field=models.CharField(default=1, max_length=4),
        ),
    ]
