# Generated by Django 5.2.3 on 2025-06-26 08:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz2', '0003_dimension_orden_alter_interestarea_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idQ', models.PositiveIntegerField(default=1)),
                ('fechaC', models.DateTimeField(auto_now_add=True)),
                ('fechaA', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='corecontent',
            options={'ordering': ['core_cont']},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='interestarea',
            options={'ordering': ['orden']},
        ),
        migrations.RemoveIndex(
            model_name='corecontent',
            name='quiz2_corec_core_co_9cce84_idx',
        ),
        migrations.RemoveField(
            model_name='option',
            name='id',
        ),
        migrations.AddField(
            model_name='option',
            name='idO',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interestarea',
            name='orden',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='dimension',
            index=models.Index(fields=['dimension'], name='quiz2_dimen_dimensi_6fe1fe_idx'),
        ),
    ]
