# Generated by Django 5.2.3 on 2025-07-14 09:49

import apps.quiz.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('enviroment', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('idO', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('profesion', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['profesion'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idQ', models.PositiveIntegerField(default=1)),
                ('fechaC', models.DateTimeField(auto_now_add=True)),
                ('fechaA', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Respondant',
            fields=[
                ('respondant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('Femenino', 'Female'), ('Masculino', 'Male')])),
                ('nationality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('level_PBE', models.PositiveSmallIntegerField(validators=[apps.quiz.utils.between1_5])),
                ('title', models.CharField(choices=[('Estudiante', 'Student'), ('Grado/Licenciatura-Diplomatura', 'Grade'), ('Master/Postgrado', 'Master'), ('Doctorado', 'Doctorate')])),
                ('year_title', models.PositiveSmallIntegerField(blank=True, null=True, validators=[apps.quiz.utils.year])),
                ('PBE_knownledge', models.BooleanField(default=False)),
                ('PBE_training', models.CharField(max_length=30)),
                ('speciality', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('idD', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('orden', models.CharField(max_length=4)),
                ('dimension', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['dimension'], name='quiz_dimens_dimensi_d984f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('idA', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('orden', models.CharField(max_length=4)),
                ('int_area', models.CharField(max_length=30)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.dimension')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CoreContent',
            fields=[
                ('idC', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('core_cont', models.CharField(max_length=30)),
                ('int_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.interestarea')),
            ],
            options={
                'ordering': ['core_cont'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idP', models.PositiveBigIntegerField(default=1, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('statement', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField()),
                ('difficult_level', models.PositiveSmallIntegerField(default=0)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.dimension')),
                ('idQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('motive', models.TextField(blank=True, max_length=250, null=True)),
                ('pk', models.CompositePrimaryKey('question', 'option', blank=True, editable=False, primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='quiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_to_question', to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(related_name='option_values', through='quiz.OptionQuestion', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('profesional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.respondant')),
                ('supervisor', models.BooleanField(default=False)),
                ('dedicationW', models.PositiveSmallIntegerField(default=0)),
                ('years', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Doctorado',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Grade',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
                ('course', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Master',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.respondant')),
                ('academic_lvl', models.PositiveSmallIntegerField()),
                ('master', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('answer', models.CharField(editable=False, max_length=25)),
                ('time', models.TimeField(editable=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('respondant', 'question', blank=True, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('respondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.respondant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Resprofs',
            fields=[
                ('pk', models.CompositePrimaryKey('profesion', 'respondant', blank=True, editable=False, primary_key=True, serialize=False)),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.profesion')),
                ('respondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.respondant')),
            ],
        ),
        migrations.AddField(
            model_name='respondant',
            name='profesions',
            field=models.ManyToManyField(related_name='profesional_area_user', through='quiz.Resprofs', to='quiz.profesion'),
        ),
        migrations.AddField(
            model_name='respondant',
            name='questions',
            field=models.ManyToManyField(related_name='respondant_answer_to_question', through='quiz.Respuesta', to='quiz.question'),
        ),
        migrations.AddIndex(
            model_name='interestarea',
            index=models.Index(fields=['int_area'], name='quiz_intere_int_are_694a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['option'], name='quiz_option_option_6354ce_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['statement'], name='quiz_questi_stateme_50f4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_doctorado',
            index=models.Index(fields=['academic_lvl'], name='quiz_stu_do_academi_f79d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_grade',
            index=models.Index(fields=['academic_lvl'], name='quiz_stu_gr_academi_d7fbad_idx'),
        ),
        migrations.AddIndex(
            model_name='stu_master',
            index=models.Index(fields=['academic_lvl'], name='quiz_stu_ma_academi_1b0daa_idx'),
        ),
    ]
