# Generated by Django 5.2.3 on 2025-07-30 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_lvl', models.CharField(choices=[('Grado', 'Grado'), ('Máster', 'Máster'), ('Doctorado', 'Doctorado')], max_length=10)),
                ('description', models.CharField(max_length=50, null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('idAct', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('idEnv', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('enviroment', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Respondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M')])),
                ('nationality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=25)),
                ('level_PBE', models.PositiveSmallIntegerField()),
                ('PBE_knownledge', models.BooleanField(default=False)),
                ('PBE_training', models.CharField(max_length=30)),
                ('speciality', models.CharField(max_length=20, null=True)),
                ('academic_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.academiclevel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionalArea',
            fields=[
                ('idA', models.AutoField(primary_key=True, serialize=False)),
                ('profarea', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['profarea'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('idQ', models.AutoField(primary_key=True, serialize=False)),
                ('fechaC', models.DateTimeField(auto_now_add=True)),
                ('fechaA', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfation',
            fields=[
                ('idSas', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('questionS', models.CharField(max_length=200)),
                ('value', models.PositiveSmallIntegerField(choices=[('Nunca', 0), ('De vez en cuando', 1), ('Menos de la mitad del tiempo', 2), ('Más de la mitad del tiempo', 3), ('La mayor parte del tiempo', 4), ('Todo el tiempo', 5)])),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('idSec', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=256, null=True, unique=True)),
                ('password', models.CharField(editable=False, max_length=256, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('idD', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField()),
                ('dimension', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['dimension'], name='quiz_dimens_dimensi_d984f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('idA', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('orden', models.CharField()),
                ('int_area', models.CharField(max_length=30)),
                ('idD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.dimension')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CoreContent',
            fields=[
                ('idC', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('core_cont', models.CharField(max_length=30)),
                ('idA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.interestarea')),
            ],
            options={
                'ordering': ['core_cont'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('idO', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=25)),
            ],
            options={
                'indexes': [models.Index(fields=['option'], name='quiz_option_option_6354ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('profesional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.respondant')),
                ('supervisor', models.BooleanField(default=False)),
                ('dedicationW', models.PositiveSmallIntegerField(default=0)),
                ('years', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='respondant',
            name='respondant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('idP', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('numero', models.PositiveBigIntegerField()),
                ('statement', models.CharField(max_length=50, unique=True)),
                ('time', models.TimeField()),
                ('difficult_level', models.PositiveSmallIntegerField()),
                ('version', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('idD', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('motive', models.TextField(max_length=250, null=True)),
                ('pk', models.CompositePrimaryKey('idP', 'idO', blank=True, editable=False, primary_key=True, serialize=False)),
                ('idO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='quiz.option')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_to_question', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('time', models.TimeField(editable=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pk', models.CompositePrimaryKey('respondant', 'question', blank=True, editable=False, primary_key=True, serialize=False)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('respondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.respondant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='interestarea',
            index=models.Index(fields=['int_area'], name='quiz_intere_int_are_694a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['statement', 'numero', 'version'], name='quiz_questi_stateme_7b0f3a_idx'),
        ),
    ]
