# Generated by Django 5.2.3 on 2025-10-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondant',
            name='profarea',
            field=models.ManyToManyField(to='quiz.profesionalarea'),
        ),
        migrations.AddField(
            model_name='respondant',
            name='question',
            field=models.ManyToManyField(related_name='respondant_answer_to_question', through='quiz.Respuesta', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='respondant',
            name='satisfation',
            field=models.ManyToManyField(related_name='satisfation_per_user', through='quiz.SatisfationRes', to='quiz.satisfation'),
        ),
        migrations.CreateModel(
            name='AppearanceQuiz',
            fields=[
                ('pk', models.CompositePrimaryKey('question', 'quiz', blank=True, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(related_name='question_in_each_quiz', through='quiz.AppearanceQuiz', to='quiz.question'),
        ),
        migrations.CreateModel(
            name='Dedication',
            fields=[
                ('percentatge', models.PositiveSmallIntegerField(default=0)),
                ('pk', models.CompositePrimaryKey('profesional', 'activity', blank=True, editable=False, primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.activity')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_between_activity_profesional', to='quiz.profesional')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='activities',
            field=models.ManyToManyField(related_name='activities_by_profesional', through='quiz.Dedication', to='quiz.activity'),
        ),
        migrations.CreateModel(
            name='Envprof',
            fields=[
                ('pk', models.CompositePrimaryKey('profesional', 'enviroment', blank=True, editable=False, primary_key=True, serialize=False)),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.enviroment')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.profesional')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='enviroments',
            field=models.ManyToManyField(related_name='enviroments_on_works', through='quiz.Envprof', to='quiz.enviroment'),
        ),
        migrations.CreateModel(
            name='Secprof',
            fields=[
                ('pk', models.CompositePrimaryKey('profesional', 'sector', blank=True, editable=False, primary_key=True, serialize=False)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.profesional')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.sector')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='sectors',
            field=models.ManyToManyField(related_name='sectors_on_works', through='quiz.Secprof', to='quiz.sector'),
        ),
    ]
