# Generated by Django 5.2.3 on 2025-11-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_respondant_profarea_respondant_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedication',
            name='percentatge',
            field=models.FloatField(default=0),
        ),
    ]
