# Generated by Django 5.2.3 on 2025-10-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_appearancequiz_quiz_question_dedication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='orden',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.CharField(max_length=100),
        ),
    ]
