# Generated by Django 5.2.3 on 2025-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_interestarea_orden_alter_quiz_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='description',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='corecontent',
            name='core_cont',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='dimension',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='interestarea',
            name='int_area',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='profesionalarea',
            name='profarea',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='satisfation',
            name='questionS',
            field=models.CharField(max_length=250),
        ),
    ]
