# Generated by Django 5.2.3 on 2025-11-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_dedication_percentatge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiclevel',
            name='year',
        ),
        migrations.RemoveField(
            model_name='respondant',
            name='academic_level',
        ),
        migrations.DeleteModel(
            name='YearAcademicLevel',
        ),
        migrations.DeleteModel(
            name='AcademicLevel',
        ),
    ]
