# Generated by Django 5.2.3 on 2025-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_academiclevel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='enviroment',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='PBE_training',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='city',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='nationality',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='region',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='speciality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(max_length=125),
        ),
    ]
