# Generated by Django 5.2.3 on 2025-11-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_academiclevel_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('idAcademicLvl', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('academic_lvl', models.CharField(choices=[('Grado', 'Grado'), ('Máster', 'Máster'), ('Doctorado', 'Doctorado')], max_length=10)),
                ('description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearAcademicLevel',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='respondant',
            name='academic_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.academiclevel'),
        ),
        migrations.AddField(
            model_name='academiclevel',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.yearacademiclevel'),
        ),
    ]

