# Generated by Django 5.2.3 on 2025-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_academiclevel_yearacademiclevel_and_more copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiclevel',
            name='idAcademicLvl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
