# Generated by Django 5.2.3 on 2025-10-12 22:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_activity_activity_alter_enviroment_enviroment_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='optionquestion',
            managers=[
                ('solutions', django.db.models.manager.Manager()),
            ],
        ),
    ]
