# Generated by Django 5.2.3 on 2025-11-08 15:56

from django.db import migrations
from apps.quiz.utils.init_data import load_data
from apps.quiz.utils.permissions import create_group


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_academiclevel_yearacademiclevel_and_more copy"),
    ]

    # i create de default values to some db classes
    operations = [
        migrations.RunPython(load_data),
        migrations.RunPython(create_group('interviewer')),
        migrations.RunPython(create_group, 'respondant'),
    ]
