# Generated by Django 5.2.3 on 2025-10-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_optionquestion_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='optionquestion',
            managers=[
            ],
        ),
    ]
