# Generated by Django 5.2.3 on 2025-12-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_academiclevel_idacademiclvl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='dedicationW',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
