# Generated by Django 5.2.3 on 2025-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_profesional_dedicationw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondant',
            name='PBE_training',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
