# Generated by Django 5.2.3 on 2025-10-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_optionquestion_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='OptionQuestion',
        ),
    ]
