# Generated by Django 5.2.3 on 2026-01-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_respondant_pbe_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='idA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.interestarea'),
        ),
        migrations.AddField(
            model_name='question',
            name='idC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.corecontent'),
        ),
    ]
