# Generated by Django 5.2.3 on 2025-10-12 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_option_question_delete_optionquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('motive', models.TextField(max_length=250, null=True)),
                ('pk', models.CompositePrimaryKey('idP', 'idO', blank=True, editable=False, primary_key=True, serialize=False)),
                ('idO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value', to='quiz.option')),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_to_question', to='quiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ManyToManyField(related_name='question_values', through='quiz.OptionQuestion', to='quiz.question'),
        ),
    ]
