# Generated by Django 5.2.3 on 2026-01-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_ida_question_idc'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
