# Generated by Django 5.2.3 on 2026-01-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_respuesta_is_correct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('respondant', 'question'), name='unique_answer_per_question'),
        ),
    ]
