# Generated by Django 5.2.3 on 2025-10-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_optionquestion_option_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionquestion',
            name='idO',
        ),
        migrations.RemoveField(
            model_name='optionquestion',
            name='idP',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveIndex(
            model_name='option',
            name='quiz_option_option_6354ce_idx',
        ),
        migrations.DeleteModel(
            name='OptionQuestion',
        ),
    ]
