# Generated by Django 5.2.3 on 2026-01-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_init_data'),
        ('quiz', '0011_respuesta_unique_answer_per_question'),
    ]

    operations = [
    ]
