# Generated by Django 5.2.3 on 2025-10-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_optionquestion_option_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='idO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='respondant',
            name='PBE_training',
            field=models.CharField(max_length=125),
        ),
    ]
