# Generated by Django 5.2.3 on 2025-10-16 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_option_ido_alter_respondant_pbe_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='idD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.dimension'),
        ),
    ]
