import uuid

from django.contrib.auth.models import AbstractUser, AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models import Q
from django.db import models
from .permissions import create_group


# Create your models here.
# The intermediate models without specific fields will be generated by Django
# ------------- QUESTION CLASS --------------
class Dimension(models.Model):
    idD =       models.SmallAutoField(primary_key=True)
    orden =     models.PositiveSmallIntegerField() 
    dimension = models.CharField(max_length=30)

    class Meta:
        indexes = [models.Index(fields=['dimension'])]
        ordering = ['orden']

    def __str__(self):
        return str('ID ' + self.id + ' Dimension ' + self.dimension)

class InterestArea(models.Model):
    idA =       models.SmallAutoField(primary_key=True)
    orden =     models.CharField()
    int_area =  models.CharField(max_length=30)
    idD = models.ForeignKey(Dimension, on_delete=models.CASCADE, null=True)

    class Meta:
        indexes = [models.Index(fields=['int_area'])]
        ordering = ['orden']

    def __str__(self):
        return str('ID ' + self.id + ' Orden '+ self.orden + ' Área de Interés ' + self.int_area + ' Dimension ' + self.dimension)
      
class CoreContent(models.Model):
    idC =       models.SmallAutoField(primary_key=True)
    core_cont = models.CharField(max_length=30)
    idA =       models.ForeignKey(InterestArea, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['core_cont']
    
    def __str__(self):
        return str('ID ' + self.id + ' Contenido Nuclear ' + self.core_cont + ' Área de interés ' + self.int_area)

class Question(models.Model): 
    class QuestionManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().values().annotate()
        
    idP =               models.BigAutoField(primary_key=True)
    numero =            models.PositiveIntegerField(default=1)
    statement =         models.CharField(max_length= 50, unique=True)  
    time =              models.TimeField()
    difficult_level =   models.PositiveSmallIntegerField()
    version =           models.PositiveIntegerField(default=0)
    date =              models.DateTimeField(auto_now=True)
    idD =               models.ForeignKey(Dimension, on_delete=models.SET_NULL, null=True)

    class Meta:
        indexes = [models.Index(fields=['statement', 'numero', 'version'])]
        
    def __str__(self):
        return str(f'ID: {self.idP}, Número: {self.numero}, Version: {self.version}, Enunciado: {self.statement}')

# Class that represents the solution at all the options, relathinship many to one with question
class Option(models.Model):
    idO =               models.AutoField(default=1, primary_key=True)
    option =            models.CharField(max_length=25)
    question =          models.ManyToManyField(Question, through='OptionQuestion', related_name='question_values')

    class Meta:
        indexes = [models.Index(fields=['option'])]    

    def __str__(self):
        return str('ID ' + self.id + ' Opción ' + self.option)

class OptionQuestion(models.Model): 
    
    # get only the solutions for each question id of all options 
    class OptionQuestionManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().values('idP').annotate('idP').exclude(Q(motive__isnull=True)|Q(motive='')|Q(motive=' ')).values('idP', 'idO', 'motive')
        
    idP =       models.ForeignKey(Question, on_delete=models.CASCADE, related_name='option_value_to_question')
    idO =       models.ForeignKey(Option, on_delete=models.CASCADE, related_name='option_value') # this id of the value
    motive =    models.TextField(max_length=250, null=True)
    pk =        models.CompositePrimaryKey('idP', 'idO')

    objects =   models.Manager() #default
    solutions=  OptionQuestionManager() 
        
    def __str__(self):
        return str('Pregunta ' + self.idP + ' Valor ' + self.idO)
    
# ------------- QUIZ CLASS --------------------
class Quiz(models.Model):
    idQ =       models.AutoField(primary_key=True)
    file =      models.CharField(max_length=20)
    fechaC =    models.DateTimeField(auto_now_add=True)
    fechaA =    models.DateTimeField(auto_now=True)
    question =  models.ManyToManyField('Question', through='AppearanceQuiz', related_name='question_in_each_quiz')

    def __str__(self):
       return str('ID: '+  self.idQ + ' fecha creación: ' + self.fechaC + ' fecha actualización:' + self.fechaA)
    
class AppearanceQuiz(models.Model):
    quiz =      models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question =  models.ForeignKey(Question, on_delete=models.CASCADE)
    pk =        models.CompositePrimaryKey('question', 'quiz')

#----------- INTERVIEWER CLASS(is MyUser) ---------
# AbstractUser to adapt default User Django Class
class MyUser(AbstractBaseUser, PermissionsMixin):
    
    class MyUserManager(BaseUserManager):
                
        def create_user(self, username, password, is_staff, **extra_fields):
            user = self.model(username, password, is_staff, **extra_fields)
                            
            if is_staff == True:
                user = self.model(username=username, is_staff=is_staff, **extra_fields)
                user.set_password(password)
            
            user.save()
            return user
        
        
        def create_superuser(self, username, password, **extra_fields):
            user = self.model(username=username, is_superuser=True, **extra_fields)
            user.set_password(password)
            
            user.save()
            return user        
            
    id =            models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, auto_created=True)
    username=       models.CharField(max_length=256, unique=True, null=True)
    password =      models.CharField(max_length=256, editable=False, null=True) 
    is_staff =      models.BooleanField(default=False)
    is_superuser =  models.BooleanField(default=False)

    objects =       MyUserManager()
    
    USERNAME_FIELD = 'username'

    def save(self, force_insert = ..., force_update = ..., using = ..., update_fields = ...):
        
        if self.is_staff is True:
            group = create_group('interviewer')
            self.groups().add(group)
            
        return super().save(force_insert, force_update, using, update_fields)

    def __str__(self):
       return str('ID: '+ + self.id + ' usuario: ' + self.username + ' password:' + self.password)  
    
 # ------------- RESPONDANT --------------------
class ProfesionalArea(models.Model):
    idA      =  models.AutoField(primary_key=True)
    profarea =  models.CharField(max_length=30)
    
    class Meta:
            ordering = ['profarea']
    
    def __str__(self):
        return str('ID: '+ self.idA +' Area Profesional: ' + self.profarea)

class Satisfation(models.Model):

    RANKING_INDIVIUAL = {
        'Nunca' :                       0,
        'De vez en cuando':             1,
        'Menos de la mitad del tiempo': 2,
        'Más de la mitad del tiempo':   3,
        'La mayor parte del tiempo':    4,
        'Todo el tiempo':               5
    }     

    idSas =     models.AutoField(primary_key=True)
    questionS =  models.CharField(max_length=200)
    value =     models.PositiveSmallIntegerField(choices=RANKING_INDIVIUAL)
    
class  AcademicLevel(models.Model):
    class AcademicLevelTypes(models.TextChoices):
        Grado = 'Grado'
        Máster = 'Máster'
        Doctorado = 'Doctorado'

    academic_lvl =  models.CharField(max_length=10, choices=AcademicLevelTypes) #academic_lvl
    description =   models.CharField(max_length=50, null=True)
    # null True permits set null in a database field
    year =          models.PositiveSmallIntegerField(null=True)
           
class Respondant(models.Model):

    class Sex(models.TextChoices):
        F = 'Femenino'
        M = 'Masculino'  

    respondant =        models.OneToOneField(MyUser, on_delete=models.CASCADE)
    age =               models.PositiveSmallIntegerField()
    sex =               models.CharField(choices=Sex)
    nationality =       models.CharField(max_length=15)
    city =              models.CharField(max_length=25)
    region =            models.CharField(max_length=25)
    level_PBE =         models.PositiveSmallIntegerField()
    PBE_knownledge =    models.BooleanField(default=False)
    PBE_training =      models.CharField(max_length=30)
    speciality =        models.CharField(max_length=20, null=True)
    academic_level =    models.ForeignKey(AcademicLevel, on_delete=models.CASCADE, null=True)
    
    
    # if i change the name to reply or answer don't works but Respuesta sí.
    question =    models.ManyToManyField(Question, through='Respuesta', related_name='respondant_answer_to_question')
    profarea =    models.ManyToManyField(ProfesionalArea, through='SatisfationGrade', related_name='profesional_area_user')
    satisfation = models.ManyToManyField(Satisfation, through='SatisfationRes', related_name='satisfation_per_user')
    
    def save(self, force_insert = ..., force_update = ..., using = ..., update_fields = ...):
        group = create_group('respondant')
        self.respondant.groups().add(group)
        return super().save(force_insert, force_update, using, update_fields)
    
    def __str__(self):
       return str('ID: '+ self.respondant.id+ ' Edad: '+self.age+ ' Sexo: '+ self.sex + ' Nacionalidad: '+ self.nationality + ' Ciudad: '+ self.city + 
                  ' Región: ' + self.region +  ' Título: '+ self.title + ' Año de titulación: '+ self.year_title + ' Area profesional/estudio: '+ 
                  self.areaprof.values_list(flat=True)+ ' Nivel de PBE: ' + self.level_PBE +' Conocimiento en PBE '+ self.PBE_knownledge + ' Especialidad: '+ self.speciality)
    
class SatisfationRes(models.Model):
    idS =   models.ForeignKey(Satisfation, on_delete=models.CASCADE)
    idRes =   models.ForeignKey(Respondant, on_delete=models.CASCADE)
    pk =    models.CompositePrimaryKey('idS', 'idRes')

class SatisfationGrade(models.Model):
    RANKING_GLOBAL = []
    for i in range(1, 10):
        RANKING_GLOBAL.append((i, str(i)))

    grade = models.PositiveSmallIntegerField(choices=RANKING_GLOBAL)
    idA =   models.ForeignKey(ProfesionalArea, on_delete=models.CASCADE)
    idRes =   models.ForeignKey(Respondant, on_delete=models.CASCADE)
    pk =    models.CompositePrimaryKey('idA', 'idRes')
    
# ------------- ANSWER CLASS --------------
# The class name is in spanish cause django don't permit other
class Respuesta(models.Model):
    answer = models.ForeignKey(Option, on_delete=models.CASCADE, null=True)# models.CharField(max_length=25, editable=False, blank=False)
    time = models.TimeField(editable=False, blank=False)
    date = models.DateTimeField(auto_now_add=True)
    respondant = models.ForeignKey(Respondant, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pk = models.CompositePrimaryKey('respondant','question')

    class Meta:
        ordering = ['-date']
    
    def __str__(self):
        return str('ID ' + self.pk + ' Enunciado ' + self.answer)

# ------------------- PROFESIONALS --------------------          
class Enviroment(models.Model):
    idEnv = models.AutoField(primary_key=True)
    enviroment = models.CharField(max_length=25)

    def __str__(self):
        return str('ID: '+self.idEnv + ' environ ' + self.environ)
    
class Sector(models.Model):
    idSec = models.AutoField(primary_key=True)
    sector = models.CharField(max_length=15)

    def __str__(self):
        return str('ID: '+self.idSec + ' sector ' + self.sector)

class Activity(models.Model):
    idAct = models.AutoField(primary_key=True)
    activity = models.CharField(max_length=20)

    def __str__(self):
        return str('ID: '+self.idAct + ' activity ' + self.activity)
    
class  Profesional(models.Model):
    profesional =   models.OneToOneField(Respondant, on_delete=models.CASCADE, primary_key=True)
    supervisor =    models.BooleanField(default=False)
    dedicationW =   models.PositiveSmallIntegerField(default=0)
    years =         models.PositiveSmallIntegerField(default=0)
    
    activities =  models.ManyToManyField(Activity, through='Dedication', related_name='activities_by_profesional')
    sectors =     models.ManyToManyField(Sector, through='Secprof', related_name='sectors_on_works')
    enviroments = models.ManyToManyField(Enviroment, through='Envprof', related_name='enviroments_on_works')

# Intermediate class between activity and profesional to show pecentatge of time that a profesional takes to do an activity
class Dedication(models.Model):
    profesional = models.ForeignKey(Profesional, on_delete=models.CASCADE, related_name='id_between_activity_profesional')
    activity =    models.ForeignKey(Activity, on_delete=models.CASCADE)
    percentatge = models.PositiveSmallIntegerField(default=0)
    pk =          models.CompositePrimaryKey('profesional','activity')
        
class  Envprof(models.Model):
    profesional = models.ForeignKey(Profesional, on_delete=models.CASCADE)
    enviroment =  models.ForeignKey(Enviroment, on_delete=models.CASCADE)
    pk =          models.CompositePrimaryKey('profesional','enviroment')

class  Secprof(models.Model): 
    profesional = models.ForeignKey(Profesional, on_delete=models.CASCADE)
    sector =      models.ForeignKey(Sector, on_delete=models.CASCADE)
    pk =          models.CompositePrimaryKey('profesional','sector')